// Code generated by codegen. DO NOT EDIT.

package code

func init() {

	register(ErrSuccess, 200, "OK")

	register(ErrUnknow, 500, "Internal server error")

	register(ErrBind, 400, "Error occurred while binding the request body to the struct")

	register(ErrValidation, 400, "Validation failed")

	register(ErrTokenInvalid, 500, "Internal server error")

	register(ErrPageNotFound, 404, "Page not found")

	register(ErrDatabase, 500, "Database error")

	register(ErrRecordNotFound, 404, "Record not found")

	register(ErrRedis, 500, "Redis error")

	register(ErrCacheNotFound, 404, "Cache not found")

	register(ErrEncrypt, 401, "Error occurred while encrypting the user password")

	register(ErrSignatureInvalid, 401, "Signature is invalid")

	register(ErrExpired, 401, "Token expired")

	register(ErrInvalidAuthHeader, 401, "Invalid authorization header")

	register(ErrMissingHeader, 401, "The `Authorization` header was missed or empty")

	register(ErrPasswordIncorrect, 401, "Password was incorrect")

	register(ErrPermissionDenied, 403, "Permission denied")

	register(ErrEncodingFailed, 500, "Encoding failed due to an error with the data")

	register(ErrDecodingFailed, 500, "Decoding failed due to an error with the data")

	register(ErrInvalidJSON, 500, "Data is not valid JSON")

	register(ErrEncodingJSON, 500, "JSON data could not be encoded")

	register(ErrDecodingJSON, 500, "JSON data could not be decoded")

	register(ErrInvalidYAML, 500, "Data is not valid YAML")

	register(ErrEncodingYAML, 500, "YAML data could not be encoded")

	register(ErrDecodingYAML, 500, "YAML data could not be decoded")

}