// Code generated by codegen. DO NOT EDIT.

package code

func init() {

	register(ErrUserNotFound, 404, "User not found")

	register(ErrUserAlreadyExists, 400, "User already exists")

	register(ErrUserPasswordIncorrect, 401, "Password was incorrect")

	register(ErrUserPasswordTooShort, 400, "Password is too short")

	register(ErrUserPasswordTooLong, 400, "Password is too long")

	register(ErrUserPasswordInvalid, 400, "Password is invalid")

	register(ErrUserPasswordNotMatch, 400, "Password not match")

	register(UserNoAuthority, 403, "User no authority")

}